package com.example.testactionbar.db;

import java.io.Serializable;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table BOOK.
 */
public class Book implements Serializable
{

    private String bookName;
    private String bookUrl;
    private String image;
    private String author;
    private String state;
    private String introduce;
    private String lastChapterUrl;
    private String lastChapterName;
    private Short chapterIndex;
    private Short chapterPageIndex;

    public Book()
    {
    }

    public Book(String bookName)
    {
        this.bookName = bookName;
    }

    public Book(String bookName, String bookUrl, String image, String author, String state,
            String introduce, String lastChapterUrl, String lastChapterName, Short chapterIndex,
            Short chapterPageIndex)
    {
        this.bookName = bookName;
        this.bookUrl = bookUrl;
        this.image = image;
        this.author = author;
        this.state = state;
        this.introduce = introduce;
        this.lastChapterUrl = lastChapterUrl;
        this.lastChapterName = lastChapterName;
        this.chapterIndex = chapterIndex;
        this.chapterPageIndex = chapterPageIndex;
    }

    public String getBookName()
    {
        return bookName;
    }

    public void setBookName(String bookName)
    {
        this.bookName = bookName;
    }

    public String getBookUrl()
    {
        return bookUrl;
    }

    public void setBookUrl(String bookUrl)
    {
        this.bookUrl = bookUrl;
    }

    public String getImage()
    {
        return image;
    }

    public void setImage(String image)
    {
        this.image = image;
    }

    public String getAuthor()
    {
        return author;
    }

    public void setAuthor(String author)
    {
        this.author = author;
    }

    public String getState()
    {
        return state;
    }

    public void setState(String state)
    {
        this.state = state;
    }

    public String getIntroduce()
    {
        return introduce;
    }

    public void setIntroduce(String introduce)
    {
        this.introduce = introduce;
    }

    public String getLastChapterUrl()
    {
        return lastChapterUrl;
    }

    public void setLastChapterUrl(String lastChapterUrl)
    {
        this.lastChapterUrl = lastChapterUrl;
    }

    public String getLastChapterName()
    {
        return lastChapterName;
    }

    public void setLastChapterName(String lastChapterName)
    {
        this.lastChapterName = lastChapterName;
    }

    public Short getChapterIndex()
    {
        return chapterIndex;
    }

    public void setChapterIndex(Short chapterIndex)
    {
        this.chapterIndex = chapterIndex;
    }

    public Short getChapterPageIndex()
    {
        return chapterPageIndex;
    }

    public void setChapterPageIndex(Short chapterPageIndex)
    {
        this.chapterPageIndex = chapterPageIndex;
    }

}
