package com.example.testactionbar.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table BOOK.
 */
public class Book {

    private String bookID;
    private String bookName;
    private String bookUrl;
    private String author;
    private String state;
    private String introduce;
    private String lastChapterUrl;
    private String lastChapterName;

    public Book() {
    }

    public Book(String bookID) {
        this.bookID = bookID;
    }

    public Book(String bookID, String bookName, String bookUrl, String author, String state, String introduce, String lastChapterUrl, String lastChapterName) {
        this.bookID = bookID;
        this.bookName = bookName;
        this.bookUrl = bookUrl;
        this.author = author;
        this.state = state;
        this.introduce = introduce;
        this.lastChapterUrl = lastChapterUrl;
        this.lastChapterName = lastChapterName;
    }

    public String getBookID() {
        return bookID;
    }

    public void setBookID(String bookID) {
        this.bookID = bookID;
    }

    public String getBookName() {
        return bookName;
    }

    public void setBookName(String bookName) {
        this.bookName = bookName;
    }

    public String getBookUrl() {
        return bookUrl;
    }

    public void setBookUrl(String bookUrl) {
        this.bookUrl = bookUrl;
    }

    public String getAuthor() {
        return author;
    }

    public void setAuthor(String author) {
        this.author = author;
    }

    public String getState() {
        return state;
    }

    public void setState(String state) {
        this.state = state;
    }

    public String getIntroduce() {
        return introduce;
    }

    public void setIntroduce(String introduce) {
        this.introduce = introduce;
    }

    public String getLastChapterUrl() {
        return lastChapterUrl;
    }

    public void setLastChapterUrl(String lastChapterUrl) {
        this.lastChapterUrl = lastChapterUrl;
    }

    public String getLastChapterName() {
        return lastChapterName;
    }

    public void setLastChapterName(String lastChapterName) {
        this.lastChapterName = lastChapterName;
    }

}
